spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/raipur_metaliks
spring.datasource.username=root
spring.datasource.password=Welcome@2025
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Local allowed CORS origins
app.cors.allowed-origins=http://localhost:5173,http://localhost:3000,https://raipurmetaliksfe-production-0be7.up.railway.app
