# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${DB_URL:jdbc:mysql://root:clwDXXyldSyAGXvJRrOqDXGFxVPFMpOZ@switchback.proxy.rlwy.net:44958/railway}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:clwDXXyldSyAGXvJRrOqDXGFxVPFMpOZ}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Production allowed CORS origins (configurable via environment variable)
app.cors.allowed-origins=${CORS_ORIGINS:https://raipurmetaliksfe-production-0be7.up.railway.app}